# Generated by Django 3.1.1 on 2020-10-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201014_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='horasa',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
    ]
